/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as FoundersRouteImport } from './routes/founders'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CourseRouteImport } from './routes/course'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LearnRouteRouteImport } from './routes/learn/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnIndexRouteImport } from './routes/learn/index'
import { Route as LearnLoginRouteImport } from './routes/learn/login'
import { Route as LearnFinalRouteImport } from './routes/learn/final'
import { Route as LearnDashboardRouteImport } from './routes/learn/dashboard'
import { Route as AdminVolunteersRouteImport } from './routes/admin.volunteers'
import { Route as LearnModulesRouteRouteImport } from './routes/learn/modules/route'
import { Route as AdminVolunteersIdsRouteImport } from './routes/admin.volunteers.ids'
import { Route as AdminVolunteersCompletedRouteImport } from './routes/admin.volunteers.completed'
import { Route as LearnModulesModuleIdRouteRouteImport } from './routes/learn/modules/$moduleId/route'
import { Route as LearnModulesModuleIdIndexRouteImport } from './routes/learn/modules/$moduleId/index'
import { Route as LearnModulesModuleIdQuizRouteImport } from './routes/learn/modules/$moduleId/quiz'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundersRoute = FoundersRouteImport.update({
  id: '/founders',
  path: '/founders',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseRoute = CourseRouteImport.update({
  id: '/course',
  path: '/course',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRouteRoute = LearnRouteRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnRouteRoute,
} as any)
const LearnLoginRoute = LearnLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LearnRouteRoute,
} as any)
const LearnFinalRoute = LearnFinalRouteImport.update({
  id: '/final',
  path: '/final',
  getParentRoute: () => LearnRouteRoute,
} as any)
const LearnDashboardRoute = LearnDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LearnRouteRoute,
} as any)
const AdminVolunteersRoute = AdminVolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => AdminRoute,
} as any)
const LearnModulesRouteRoute = LearnModulesRouteRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => LearnRouteRoute,
} as any)
const AdminVolunteersIdsRoute = AdminVolunteersIdsRouteImport.update({
  id: '/ids',
  path: '/ids',
  getParentRoute: () => AdminVolunteersRoute,
} as any)
const AdminVolunteersCompletedRoute =
  AdminVolunteersCompletedRouteImport.update({
    id: '/completed',
    path: '/completed',
    getParentRoute: () => AdminVolunteersRoute,
  } as any)
const LearnModulesModuleIdRouteRoute =
  LearnModulesModuleIdRouteRouteImport.update({
    id: '/$moduleId',
    path: '/$moduleId',
    getParentRoute: () => LearnModulesRouteRoute,
  } as any)
const LearnModulesModuleIdIndexRoute =
  LearnModulesModuleIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LearnModulesModuleIdRouteRoute,
  } as any)
const LearnModulesModuleIdQuizRoute =
  LearnModulesModuleIdQuizRouteImport.update({
    id: '/quiz',
    path: '/quiz',
    getParentRoute: () => LearnModulesModuleIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/learn': typeof LearnRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/course': typeof CourseRoute
  '/faq': typeof FaqRoute
  '/founders': typeof FoundersRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/programs': typeof ProgramsRoute
  '/research': typeof ResearchRoute
  '/volunteer': typeof VolunteerRoute
  '/learn/modules': typeof LearnModulesRouteRouteWithChildren
  '/admin/volunteers': typeof AdminVolunteersRouteWithChildren
  '/learn/dashboard': typeof LearnDashboardRoute
  '/learn/final': typeof LearnFinalRoute
  '/learn/login': typeof LearnLoginRoute
  '/learn/': typeof LearnIndexRoute
  '/learn/modules/$moduleId': typeof LearnModulesModuleIdRouteRouteWithChildren
  '/admin/volunteers/completed': typeof AdminVolunteersCompletedRoute
  '/admin/volunteers/ids': typeof AdminVolunteersIdsRoute
  '/learn/modules/$moduleId/quiz': typeof LearnModulesModuleIdQuizRoute
  '/learn/modules/$moduleId/': typeof LearnModulesModuleIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/course': typeof CourseRoute
  '/faq': typeof FaqRoute
  '/founders': typeof FoundersRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/programs': typeof ProgramsRoute
  '/research': typeof ResearchRoute
  '/volunteer': typeof VolunteerRoute
  '/learn/modules': typeof LearnModulesRouteRouteWithChildren
  '/admin/volunteers': typeof AdminVolunteersRouteWithChildren
  '/learn/dashboard': typeof LearnDashboardRoute
  '/learn/final': typeof LearnFinalRoute
  '/learn/login': typeof LearnLoginRoute
  '/learn': typeof LearnIndexRoute
  '/admin/volunteers/completed': typeof AdminVolunteersCompletedRoute
  '/admin/volunteers/ids': typeof AdminVolunteersIdsRoute
  '/learn/modules/$moduleId/quiz': typeof LearnModulesModuleIdQuizRoute
  '/learn/modules/$moduleId': typeof LearnModulesModuleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/learn': typeof LearnRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/course': typeof CourseRoute
  '/faq': typeof FaqRoute
  '/founders': typeof FoundersRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/programs': typeof ProgramsRoute
  '/research': typeof ResearchRoute
  '/volunteer': typeof VolunteerRoute
  '/learn/modules': typeof LearnModulesRouteRouteWithChildren
  '/admin/volunteers': typeof AdminVolunteersRouteWithChildren
  '/learn/dashboard': typeof LearnDashboardRoute
  '/learn/final': typeof LearnFinalRoute
  '/learn/login': typeof LearnLoginRoute
  '/learn/': typeof LearnIndexRoute
  '/learn/modules/$moduleId': typeof LearnModulesModuleIdRouteRouteWithChildren
  '/admin/volunteers/completed': typeof AdminVolunteersCompletedRoute
  '/admin/volunteers/ids': typeof AdminVolunteersIdsRoute
  '/learn/modules/$moduleId/quiz': typeof LearnModulesModuleIdQuizRoute
  '/learn/modules/$moduleId/': typeof LearnModulesModuleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/learn'
    | '/about'
    | '/admin'
    | '/careers'
    | '/contact'
    | '/course'
    | '/faq'
    | '/founders'
    | '/join'
    | '/login'
    | '/programs'
    | '/research'
    | '/volunteer'
    | '/learn/modules'
    | '/admin/volunteers'
    | '/learn/dashboard'
    | '/learn/final'
    | '/learn/login'
    | '/learn/'
    | '/learn/modules/$moduleId'
    | '/admin/volunteers/completed'
    | '/admin/volunteers/ids'
    | '/learn/modules/$moduleId/quiz'
    | '/learn/modules/$moduleId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/careers'
    | '/contact'
    | '/course'
    | '/faq'
    | '/founders'
    | '/join'
    | '/login'
    | '/programs'
    | '/research'
    | '/volunteer'
    | '/learn/modules'
    | '/admin/volunteers'
    | '/learn/dashboard'
    | '/learn/final'
    | '/learn/login'
    | '/learn'
    | '/admin/volunteers/completed'
    | '/admin/volunteers/ids'
    | '/learn/modules/$moduleId/quiz'
    | '/learn/modules/$moduleId'
  id:
    | '__root__'
    | '/'
    | '/learn'
    | '/about'
    | '/admin'
    | '/careers'
    | '/contact'
    | '/course'
    | '/faq'
    | '/founders'
    | '/join'
    | '/login'
    | '/programs'
    | '/research'
    | '/volunteer'
    | '/learn/modules'
    | '/admin/volunteers'
    | '/learn/dashboard'
    | '/learn/final'
    | '/learn/login'
    | '/learn/'
    | '/learn/modules/$moduleId'
    | '/admin/volunteers/completed'
    | '/admin/volunteers/ids'
    | '/learn/modules/$moduleId/quiz'
    | '/learn/modules/$moduleId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LearnRouteRoute: typeof LearnRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  CourseRoute: typeof CourseRoute
  FaqRoute: typeof FaqRoute
  FoundersRoute: typeof FoundersRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  ProgramsRoute: typeof ProgramsRoute
  ResearchRoute: typeof ResearchRoute
  VolunteerRoute: typeof VolunteerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founders': {
      id: '/founders'
      path: '/founders'
      fullPath: '/founders'
      preLoaderRoute: typeof FoundersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course': {
      id: '/course'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof CourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof LearnRouteRoute
    }
    '/learn/login': {
      id: '/learn/login'
      path: '/login'
      fullPath: '/learn/login'
      preLoaderRoute: typeof LearnLoginRouteImport
      parentRoute: typeof LearnRouteRoute
    }
    '/learn/final': {
      id: '/learn/final'
      path: '/final'
      fullPath: '/learn/final'
      preLoaderRoute: typeof LearnFinalRouteImport
      parentRoute: typeof LearnRouteRoute
    }
    '/learn/dashboard': {
      id: '/learn/dashboard'
      path: '/dashboard'
      fullPath: '/learn/dashboard'
      preLoaderRoute: typeof LearnDashboardRouteImport
      parentRoute: typeof LearnRouteRoute
    }
    '/admin/volunteers': {
      id: '/admin/volunteers'
      path: '/volunteers'
      fullPath: '/admin/volunteers'
      preLoaderRoute: typeof AdminVolunteersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/learn/modules': {
      id: '/learn/modules'
      path: '/modules'
      fullPath: '/learn/modules'
      preLoaderRoute: typeof LearnModulesRouteRouteImport
      parentRoute: typeof LearnRouteRoute
    }
    '/admin/volunteers/ids': {
      id: '/admin/volunteers/ids'
      path: '/ids'
      fullPath: '/admin/volunteers/ids'
      preLoaderRoute: typeof AdminVolunteersIdsRouteImport
      parentRoute: typeof AdminVolunteersRoute
    }
    '/admin/volunteers/completed': {
      id: '/admin/volunteers/completed'
      path: '/completed'
      fullPath: '/admin/volunteers/completed'
      preLoaderRoute: typeof AdminVolunteersCompletedRouteImport
      parentRoute: typeof AdminVolunteersRoute
    }
    '/learn/modules/$moduleId': {
      id: '/learn/modules/$moduleId'
      path: '/$moduleId'
      fullPath: '/learn/modules/$moduleId'
      preLoaderRoute: typeof LearnModulesModuleIdRouteRouteImport
      parentRoute: typeof LearnModulesRouteRoute
    }
    '/learn/modules/$moduleId/': {
      id: '/learn/modules/$moduleId/'
      path: '/'
      fullPath: '/learn/modules/$moduleId/'
      preLoaderRoute: typeof LearnModulesModuleIdIndexRouteImport
      parentRoute: typeof LearnModulesModuleIdRouteRoute
    }
    '/learn/modules/$moduleId/quiz': {
      id: '/learn/modules/$moduleId/quiz'
      path: '/quiz'
      fullPath: '/learn/modules/$moduleId/quiz'
      preLoaderRoute: typeof LearnModulesModuleIdQuizRouteImport
      parentRoute: typeof LearnModulesModuleIdRouteRoute
    }
  }
}

interface LearnModulesModuleIdRouteRouteChildren {
  LearnModulesModuleIdQuizRoute: typeof LearnModulesModuleIdQuizRoute
  LearnModulesModuleIdIndexRoute: typeof LearnModulesModuleIdIndexRoute
}

const LearnModulesModuleIdRouteRouteChildren: LearnModulesModuleIdRouteRouteChildren =
  {
    LearnModulesModuleIdQuizRoute: LearnModulesModuleIdQuizRoute,
    LearnModulesModuleIdIndexRoute: LearnModulesModuleIdIndexRoute,
  }

const LearnModulesModuleIdRouteRouteWithChildren =
  LearnModulesModuleIdRouteRoute._addFileChildren(
    LearnModulesModuleIdRouteRouteChildren,
  )

interface LearnModulesRouteRouteChildren {
  LearnModulesModuleIdRouteRoute: typeof LearnModulesModuleIdRouteRouteWithChildren
}

const LearnModulesRouteRouteChildren: LearnModulesRouteRouteChildren = {
  LearnModulesModuleIdRouteRoute: LearnModulesModuleIdRouteRouteWithChildren,
}

const LearnModulesRouteRouteWithChildren =
  LearnModulesRouteRoute._addFileChildren(LearnModulesRouteRouteChildren)

interface LearnRouteRouteChildren {
  LearnModulesRouteRoute: typeof LearnModulesRouteRouteWithChildren
  LearnDashboardRoute: typeof LearnDashboardRoute
  LearnFinalRoute: typeof LearnFinalRoute
  LearnLoginRoute: typeof LearnLoginRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

const LearnRouteRouteChildren: LearnRouteRouteChildren = {
  LearnModulesRouteRoute: LearnModulesRouteRouteWithChildren,
  LearnDashboardRoute: LearnDashboardRoute,
  LearnFinalRoute: LearnFinalRoute,
  LearnLoginRoute: LearnLoginRoute,
  LearnIndexRoute: LearnIndexRoute,
}

const LearnRouteRouteWithChildren = LearnRouteRoute._addFileChildren(
  LearnRouteRouteChildren,
)

interface AdminVolunteersRouteChildren {
  AdminVolunteersCompletedRoute: typeof AdminVolunteersCompletedRoute
  AdminVolunteersIdsRoute: typeof AdminVolunteersIdsRoute
}

const AdminVolunteersRouteChildren: AdminVolunteersRouteChildren = {
  AdminVolunteersCompletedRoute: AdminVolunteersCompletedRoute,
  AdminVolunteersIdsRoute: AdminVolunteersIdsRoute,
}

const AdminVolunteersRouteWithChildren = AdminVolunteersRoute._addFileChildren(
  AdminVolunteersRouteChildren,
)

interface AdminRouteChildren {
  AdminVolunteersRoute: typeof AdminVolunteersRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminVolunteersRoute: AdminVolunteersRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LearnRouteRoute: LearnRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  CourseRoute: CourseRoute,
  FaqRoute: FaqRoute,
  FoundersRoute: FoundersRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  ProgramsRoute: ProgramsRoute,
  ResearchRoute: ResearchRoute,
  VolunteerRoute: VolunteerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
